apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deploy
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-deploy
  template:
    metadata:
      labels:
        app: redis-deploy
    spec:
      containers:
        - name: redis-container
          image: 192.168.80.6:1180/qa/spring-boot-sample-redis:2.1.8.2
          ports:
            - containerPort: 10004
---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: dev
spec:
  selector:
    app: redis-deploy
  type: NodePort
  ports:
    - port: 10005
      targetPort: 10004
